name: Cypress Tests

on:
  push:
    branches:
      - testing
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Install Dependencies
        run: npm install
      - name: Set Cypress Environment Variables
        run: |
          echo "CYPRESS_GENERAL_USER_USERNAME=${{ secrets.CYPRESS_GENERAL_USER_USERNAME }}" >> $GITHUB_ENV
          echo "CYPRESS_GENERAL_USER_PASSWORD=${{ secrets.CYPRESS_GENERAL_USER_PASSWORD }}" >> $GITHUB_ENV

          echo "CYPRESS_STAF_USERNAME=${{ secrets.CYPRESS_STAF_USERNAME }}" >> $GITHUB_ENV
          echo "CYPRESS_STAF_PASSWORD=${{ secrets.CYPRESS_STAF_PASSWORD }}" >> $GITHUB_ENV

          echo "CYPRESS_ADMIN_USERNAME=${{ secrets.CYPRESS_ADMIN_USERNAME }}" >> $GITHUB_ENV
          echo "CYPRESS_ADMIN_PASSWORD=${{ secrets.CYPRESS_ADMIN_PASSWORD }}" >> $GITHUB_ENV

          echo "CYPRESS_SUPERADMIN_USERNAME=${{ secrets.CYPRESS_SUPERADMIN_USERNAME }}" >> $GITHUB_ENV
          echo "CYPRESS_SUPERADMIN_PASSWORD=${{ secrets.CYPRESS_SUPERADMIN_PASSWORD }}" >> $GITHUB_ENV

          echo "CYPRESS_ADMS_USERNAME=${{ secrets.ADMS_USERNAME }}" >> $GITHUB_ENV
          echo "CYPRESS_ADMS_PASSWORD=${{ secrets.ADMS_PASSWORD }}" >> $GITHUB_ENV

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm run dev